### ISSUE TITLE
If customer has no payment methods, returns [nil] instead of []

### ISSUE THREAD

**Issue by deremer** [braintree/braintree_ruby#100]
If you execute
```
customer = Braintree::Customer.find(customer_id)
```
Then get the customer's payment methods:
```
customer.payment_methods
 => [nil] 
```
The result is an array of length 1 where the value is nil. This is not equivalent to [ ], so things like .present? and .empty? do not work

**Comment by omgrr** [comment]
I tried to reproduce this but I get the expected `[]`. Do you have a full example of this? 

Also, what ruby and gem version are you using?

```
Braintree::Customer.create(id: "1")
customer = Braintree::Customer.find("1")

customer.payment_methods
# []
```

**Comment by deremer** [comment]
Hmm. Did 'bundle update braintree' and now seems to work ok.. a bit odd b/c it doesn't seem to have updated version number. Perhaps there was something weird about the individual customer's payment methods. At any rate, seems to be working ok now and I have checks in place just in case. Thanks for the time spent taking a lookl
