### ISSUE TITLE
Updated_at Transaction search field.

### ISSUE THREAD

**Issue by prburke** [braintree/braintree_ruby#101]
Is there any chance that we could get ```updated_at``` added as a Transaction search field?

It would need to be added here and supported on the backend:

https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/transaction_search.rb#L66

Transaction search results include both a ```created_at``` and ```updated_at``` attribute, but only  ```created_at``` is currently available as a search field.  Given that it isn't possible to OR search conditions, being able to search by ```updated_at``` would help us out a lot.

**Comment by ryanjpodonnell** [comment]
@prburke Thanks for brining this to our attention. We generally suggest using the status timestamps (created_at, authorized_at, settled_at, etc.) to query and track the lifecycle of transactions as the `updated_at` field doesn’t give any indication of what has changed.

Can I ask what you need this functionality for?

**Comment by prburke** [comment]
Hi @ryanjpodonnell, thanks for the reply.  We want to be able to track the latest transaction status transitions in a given time period.  Currently to do this we have to issue a separate query on each status timestamp which leads to lots of data being retrieved that we just throw away and extra local processing.  Being able to search by updated_at, or having a way to `or` conditions on different timestamps would make this much easier and efficient for us. 

Are there cases where the updated_at attribute on a transaction does not correspond to its last status transition time?  If so, and it is not possible to determine what has changed on the transaction when this attribute is updated, what is the value of exposing it in the api?  I'm just curious to know how it was intended to be used.

**Comment by raymondberg** [comment]
Hi @pburke, thanks for clarifying. It's an interesting idea for us to consider, but it would take some more work to integrate in our search logic (as you point out). I'm also not sure we could ever guarantee that the Transaction object updated at corresponds only to a Transaction status change, and it checking Transaction for status changes certainly be brittle if we add other functionality to Transaction in the future. 

As for its use, the `updated_at` field is commonly used in other workflows when, for example, reviewing contested Transactions that have been pulled down through another search, hence it's inclusion in the client library. I'm going to close this issue for now, but we'll consider it for future iterations of the client libraries. Thanks for the suggestion!

**Comment by kgoutham** [comment]
Hello , We are encountering similar issue , Is there any workaround for this ? @prburke
