### ISSUE TITLE
subscription update raising NotFoundError (sandbox)

### ISSUE THREAD

**Issue by murtyk** [braintree/braintree_ruby#104]
[development] [2] Vydia(main)> def simple_update(id)
[development] [2] Vydia(main)*   result = Braintree::Subscription.update(  
[development] [2] Vydia(main)*     id, # id of subscription to update    
[development] [2] Vydia(main)*     :payment_method_token => "fake-valid-nonce"    
[development] [2] Vydia(main)*   )    
[development] [2] Vydia(main)* end  
=> :simple_update
[development] [3] Vydia(main)> result = simple_update(sub.id)
D, [2015-12-11T20:46:12.558506 #28801] DEBUG -- : [httplog] Connecting: api.sandbox.braintreegateway.com:443
D, [2015-12-11T20:46:12.802264 #28801] DEBUG -- : [httplog] Sending: PUT http://api.sandbox.braintreegateway.com:443/merchants/bss316yxzp7wg9sd/subscriptions/752v2m
D, [2015-12-11T20:46:12.802728 #28801] DEBUG -- : [httplog] Data: <?xml version="1.0" encoding="UTF-8"?>
<subscription>
  <payment-method-token>fake-valid-nonce</payment-method-token>
</subscription>

D, [2015-12-11T20:46:13.052371 #28801] DEBUG -- : [httplog] Status: 404
D, [2015-12-11T20:46:13.052821 #28801] DEBUG -- : [httplog] Benchmark: 0.24797862 seconds
D, [2015-12-11T20:46:13.053197 #28801] DEBUG -- : [httplog] Response: (deflated)

I, [2015-12-11T20:46:13.054127 #28801]  INFO -- : [Braintree] [11/Dec/2015 20:46:13 UTC] PUT /merchants/bss316yxzp7wg9sd/subscriptions/752v2m 404
Braintree::NotFoundError: Braintree::NotFoundError
from /var/lib/gems/2.1.0/gems/braintree-2.56.0/lib/braintree/util.rb:55:in `raise_exception_for_status_code'
[development] [4] Vydia(main)> sub.class
=> Braintree::Subscription
[development] [5] Vydia(main)> sub.id
=> "752v2m"

**Comment by raymondberg** [comment]
Hi, @murtyk! This is not a great forum for discussing individual problems with an integration. I would encourage you to [contact Braintree support](https://support.braintreepayments.com) to provide more specifics about your environment and the problem you are experiencing.
