### ISSUE TITLE
Add creation_date as a filter to Braintree::Subscription.search

### ISSUE THREAD

**Issue by eshem** [braintree/braintree_ruby#107]
I need to view a list of subscriptions created on a particular date. The only date filter in ```Braintree::Subscription.search``` is ```:next_billing_date```, and that is not always the same as the transaction creation date.

I would be happy to use ```Braintree::Transaction.search``` (which has ```:created_at```), however the response, ```Braintree::Transaction::SubscriptionDetails```, only lists ```billing_period_start_date``` and ```billing_period_end_date```.

Alternatively, if you added ```:subscription_id``` to ```Braintree::Transaction::SubscriptionDetails```, which seems very logical, that would solve my issue.

Thanks!

**Comment by jdlc** [comment]
Hi @eshem,
​
You're trying to find the date a subscription was first charged, correct? You can use [subscription webhooks](https://developers.braintreepayments.com/reference/general/webhooks/subscription/ruby) to get notified whenever a `subscription_went_active` event fires. This event corresponds to the first authorized transaction on a subscription. This won't help you with past subscriptions, however.
​
Could you further explain your use case for this request? Thanks!

**Comment by eshem** [comment]
Hey @jdlc,

I am using subscription webhooks elsewhere, thank you. Logically it makes sense to be able to search by ```:created_at``` for a subscription, similar to how it is possible for a transaction.

Main use case: I need to see subscriptions on a particular date, along with them, I need to see if a promotion was used. Currently, I can only see the ```amount``` of the transaction. Not really helpful if you have more than one discount that achieves the same effective amount.

Using transaction search, I can find the ```amount``` and the ```billing dates``` of the subscription, but not the ```id``` or ```discount details```. Using the subscription search, I am unable to pin down the date the subscription was created. 

Let me know if this is still unclear - thanks!

**Comment by jdlc** [comment]
@eshem
​
Thanks for explaining. Have you tried inspecting the [discounts attribute](https://developers.braintreepayments.com/reference/response/discount/ruby) 
on the [transactions](https://developers.braintreepayments.com/reference/response/transaction/ruby#discounts) or [subscriptions](https://developers.braintreepayments.com/reference/response/subscription/ruby#discounts) result objects? You'll be able to see what discounts were applied to a transaction by name and id. Please feel free to reach out to [Braintree support](https://support.braintreepayments.com) if you need any additional help with this.
​
We'll consider adding `created_at` to Subscription.search in a future iteration of the Braintree client libraries. For now I'm closing the issue, and thanks again for your idea.

**Comment by eshem** [comment]
No worries, thanks @jdlc. I have reviewed (and use) all of the results objects. My use case can be achieved through workarounds, but it would be a lot more convenient (less hits) and logical via the way I mentioned above.

There is already a ```Braintree::Transaction::SubscriptionDetails``` in transactions, why not include the subscription ID there, as well? :smile: 

Thanks again!
