### ISSUE TITLE
unable convert response object for transaction to json

### ISSUE THREAD

**Issue by chirag7jain** [braintree/braintree_ruby#112]
I have requirement where i need to store everything that comes from the payment gateway in the db

result = Braintree::Transaction.sale( :amount => "100.00", :payment_method_nonce => 'fake-valid-visa-nonce ',  :options => {  :submit_for_settlement => true } )

apparently system methods like to_json aren't working..

can you please provide a way to do this...

**Comment by pblesi** [comment]
If you are looking to store everything returned from Braintree into a database, you can call

`YAML::dump(result)`

We don't add serialization methods to the client library to keep it lightweight.

**Comment by chirag7jain** [comment]
How do I get the raw response?

**Comment by januszm** [comment]
@pblesi this actually could be very useful, eg. to process the result in a background job that requires serialization.

What is the recommended way to convert the `Braintree::Transaction` instance to a Hash ?

**Comment by pblesi** [comment]
@januszm 

Generally we suggest that you utilize Ruby's native serialization methods (`YAML::dump(transaction)`). This will work better if you want to re-materialize the object for use in Ruby. If you are looking for something that is more json-like, you could do something like the following:

```
(transaction.instance_variables - [:@gateway]).reduce({}) do |hash, var|
  hash[var.to_s[1..-1]] = transaction.instance_variable_get(var)
  hash
end.to_json
```

**Comment by januszm** [comment]
Thanks @pblesi I already resolved that with a `presenter` class:

```ruby
class TransactionPresenter
  attr_reader :transaction

  def initialize(transaction)
    @transaction = transaction
  end

  def to_hash
    {
      id: @transaction.id,
      amount: @transaction.amount,
      created_at: @transaction.created_at.strftime("%e %b %Y %I:%M:%S%p"),
      credit_card_details: {
        bin: @transaction.credit_card_details.bin,
  # ...
```

**Comment by pblesi** [comment]
Excellent! That seems like a much more robust, future-proof solution.

**Comment by januszm** [comment]
yeah I spoke with @agfor on ChiPy and now I understand why you decided to not include serialisation methods for all Braintree classes.
