### ISSUE TITLE
Batch get by IDs

### ISSUE THREAD

**Issue by jtmarmon** [braintree/braintree_ruby#113]
We'd like to get a bunch of transactions to display their statuses to the user. I'm aware you can use the search API for this functionality:

```rb
Braintree::Transaction.search do |s|
 s.ids.in ids
end
```

However, if all I want is to retrieve 3 ids, the tradeoff of using the search API makes no sense. In fact, it seems using the search API is only efficient if I have _7_ or more transactions to retrieve. Otherwise, it's actually more efficient to do a Braintree::Transaction.find N times:

```rb
[20] pry(main)> Benchmark.measure { Braintree::Transaction.search { |s| s.ids.in ids[0..20] }.map(&:id) }
I, [2016-03-16T10:43:07.411644 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:07 UTC] POST /merchants/8s32zbbpvxn5pfkp/transactions/advanced_search_ids 200
I, [2016-03-16T10:43:09.860159 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:09 UTC] POST /merchants/8s32zbbpvxn5pfkp/transactions/advanced_search 200
=> #<Benchmark::Tms:0x007fd1738515f0 @cstime=0.0, @cutime=0.0, @label="", @real=3.877907417016104, @stime=0.019999999999999907, @total=0.30000000000000016, @utime=0.28000000000000025>
[21] pry(main)> Benchmark.measure { ids[0..7].each { |id| Braintree::Transaction.find(id) } }
I, [2016-03-16T10:43:13.625833 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:13 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/6df77h 200
I, [2016-03-16T10:43:14.119012 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:14 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/4pnr3h 200
I, [2016-03-16T10:43:14.629498 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:14 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/4k8757 200
I, [2016-03-16T10:43:15.072992 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:15 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/24zjch 200
I, [2016-03-16T10:43:15.515163 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:15 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/b7whsh 200
I, [2016-03-16T10:43:15.988668 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:15 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/fxptfs 200
I, [2016-03-16T10:43:16.437729 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:16 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/b5x9bx 200
I, [2016-03-16T10:43:16.956561 #66101]  INFO -- : [Braintree] [16/Mar/2016 14:43:16 UTC] GET /merchants/8s32zbbpvxn5pfkp/transactions/24r3d3 200
=> #<Benchmark::Tms:0x007fd1713724f0 @cstime=0.0, @cutime=0.0, @label="", @real=3.782703055010643, @stime=0.030000000000000027, @total=0.19000000000000106, @utime=0.16000000000000103>
```

Is there a way braintree could support doing a standard get by N ids?

**Comment by jtmarmon** [comment]
Also, can anyone from the braintree team comment on whether these benchmarks are better in production? having a 4 second response time for simply loading transaction history is hideous in a real app...

**Comment by jtmarmon** [comment]
Here's my workaround for whoever else runs into this issue:
```rb
require 'thread'
ids = ... # somehow get ids
txs = []
mutex = Mutex.new

ids.each do |id| 
  Thread.new do
    tx = Braintree::Transaction.find(id)
    mutex.synchronize { txs.push(tx) } 
  end
end
```

**Comment by jdlc** [comment]
@jtmarmon,
Thanks for your question and for your analysis! Transaction.search and Transaction.find use different tools for lookup, which is why you see the discrepancy in response times. Additionally, sandbox performance is very different from production performance, so you should not design your integration based on sandbox performance.
At this time we don't have a plan to change the way these searches are performed, so I'm closing this issue.

**Comment by jtmarmon** [comment]
@jdlc - we're not in production yet so I can't check for myself. do you have any info on what search performance is like in production?

**Comment by jdlc** [comment]
@jtmarmon,
There are many factors that affect performance, so we can't provide specific metrics for the prod environment. I would suggest creating small test transactions in production, once you have access, as detailed [here](https://developers.braintreepayments.com/start/go-live/ruby#test-transactions-in-production).  Then you can analyze the performance of the different searches yourself.
