### ISSUE TITLE
No :created_at search field on subscriptions

### ISSUE THREAD

**Issue by thatandyrose** [braintree/braintree_ruby#114]
Hi Braintree fine folk!

Please please please (please) could you add `:created_at` to the `subscription_search`?

I'd like to be able to order by subscription queries by date (since there's are more than 10000 subscriptions)

Help!

Thanks :heart:

**Comment by jdlc** [comment]
Hi @thatandyrose,
​
Thanks for reaching out to us! This isn't the first time this feature has been requested (https://github.com/braintree/braintree_ruby/issues/107), and we have been keeping it in mind for a possible future release. Have you tried narrowing down your search by one of the [search parameters that is currently available on Subscription.search] (https://developers.braintreepayments.com/reference/request/subscription/search/ruby)? That may help reduce your set of 10,000 subscriptions to something more manageable.
​
I'm closing this issue, but thanks again for your suggestion!

**Comment by thatandyrose** [comment]
@jdlc 😢 

Cool, thanks for the reply Jessica. Hey, quick question... I can "search" for subscirption by providing an array of ids. Is that right? If so is there a limit on that search array?

Thanks! 😭

**Comment by jdlc** [comment]
Correct, you can search on `ids` and there is no limit on the search array.

**Comment by thatandyrose** [comment]
@jdlc thanks so much! 👍
