### ISSUE TITLE
Subscription/StatusDetail doesn't contain currency information

### ISSUE THREAD

**Issue by thatandyrose** [braintree/braintree_ruby#122]
hey guys, regarding the 'StatusDetail' class:

https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/subscription/status_details.rb

It's super useful since it provides a snapshot of the subscription at a certain time. HOWEVER, it is possible for a merchant to carry out, say, a subscription upgrade by simply updating the Subscription object with a new Plan.

If this new Plan has a different currency to the old plan (it's possible no?) then you will never know from the StatusDetails object which currency the amount refers to.

Does that make sense?

**Comment by mtmarsh3** [comment]
Hi @thatandyrose,

Thanks for the question! Currently, updating the `plan_id` of a `Subscription` does not actually change the price of the `Subscription`, it only [associates it with a new `Plan`](https://developers.braintreepayments.com/reference/request/subscription/update/ruby#plan_id).

Since the price doesn't actually change to that of the new `Plan`, reflecting the change in currency is not really needed.

**Comment by thatandyrose** [comment]
hi @mtmarsh3, thanks for the reply!

Hmm, sorry, I might need some clarification on something if that's cool?

Ok, say I create a very simple subscription like this:

`subscription: {price: 9.99, plan: {name: 'cheapplan', currency_iso_code: 'USD', price: 9.99}}`
`status_detail: {timestamp: '2016-07-10', price: 9.99}`

And then say I update it with a new plan and new price. Essentially I do an upgrade to a new plan for a customer (I get that that might not be best practice, but that the behaviors of a lot of Braintree users).

Now you'll have this:

`subscription: {price: 18.99, plan: {name: 'expensiveplan', currency_iso_code: 'GBP', price: 18.99}}`
`status_detail: {timestamp: '2016-07-10', price: 9.99}`
`status_detail: {timestamp: '2016-07-12', price: 18.99}`

Ok, now see the data above. If I want to know what price the subscription was before then 2016-07-12 there's no way for me to know. Yes I can see it's 9.99, but 9.99 what? I could look at the currency of the current plan, but that's actually wrong in this case. There's nothing to tell me that it was 9.99 USD. That information has been lost.

Does that make sense?

**Comment by mtmarsh3** [comment]
Thanks for the example, that definitely makes sense. We agree that having the `currency_iso_code` inside the `Status_Detail` would be useful and are implementing a fix for that right now. We will get back to you after its fixed.

**Comment by thatandyrose** [comment]
@mtmarsh3 great! What would be awesome is if you included more general subscription data... so status_detail is more like a snapshot. So, not only could you include the currency, but the actual plan_id. That would be AMAZING as it wouldn't require guessing which plan belonged to the subscription at a certain time.

In any case currency_iso_code would help.

thanks so much!

**Comment by omgrr** [comment]
Hey @thatandyrose, adding the `currency_iso_code` went out with 2.66.0! We'll be adding `plan_id` to the `status_detail` as well in a future release.

**Comment by thatandyrose** [comment]
@omgrr 👯 👯 👯 🍨 🍕 🎈 🎈 🎈  AWESOME! Thanks so much, looking forward to future releases! :-)

**Comment by jackellenberger** [comment]
Hey @thatandyrose,

The `plan_id` change just went out with [2.67.0](https://github.com/braintree/braintree_ruby/releases/tag/2.67.0), let us know how it works for you!
