### ISSUE TITLE
Switch merchant accounts (Braintree credentials) dynamically

### ISSUE THREAD

**Issue by matixmatix** [braintree/braintree_ruby#123]
I have a situation in my application where I need to switch Braintree merchant accounts (making sales with different `merchant_id`, `public_key`, `public_key`), depending on some condition.

I discovered a couple of similar issues: #89, #91, leading me to the following code from @wjr1985: [gist](https://gist.github.com/wjr1985/567445781a06e126a286), but doing it like this looks really dangerous - it doesn't look thread safe. 

Has anybody came up with a better, thread safe solution for this and can share some code? Thanks!

**Comment by jackellenberger** [comment]
Hi @matixmatix,

wjr1985 mentioned the Partners API in https://github.com/braintree/braintree_ruby/issues/89 and that is still the best option from a security standpoint. It has been expanded and rebranded as Braintree Auth, with [documentation available](https://developers.braintreepayments.com/guides/braintree-auth/overview) as well as an [example integration](https://github.com/braintree/braintree-auth-example) to help get you started.

Your other option would be an altered version of that [gist](https://gist.github.com/wjr1985/567445781a06e126a286), using [initialize(config)](https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/gateway.rb#L5)

**Comment by jackellenberger** [comment]
@matixmatix Not at the moment, it is only currently available to merchants in the US that settle in USD. However, we are working on expanding to other regions shortly. Feel free to email auth@braintreepayments.com if you'd like to learn more.
