### ISSUE TITLE
Merchant name, email and others fields

### ISSUE THREAD

**Issue by shkarlat** [braintree/braintree_ruby#124]
How can I get merchant user fields? I have a task to code Braintree Auth API in parallel with Stripe Auth. I see these fields in Stripe, but can't find it in Braintree Auth.

Thanks for any help.

**Comment by pblesi** [comment]
@shkarlat Braintree provides two separate products depending on what your use case is. Braintree provides [Braintree Auth](https://developers.braintreepayments.com/guides/braintree-auth/overview) and [Braintree Marketplace](https://developers.braintreepayments.com/guides/braintree-marketplace/overview). These correspond to Stripe's [Standalone Accounts](https://stripe.com/docs/connect/standalone-accounts) and [Managed Accounts](https://stripe.com/docs/connect/managed-accounts) respectively. 

Which product you should use depends on your use case. Braintree Auth allows you to assume the identity of other existing Braintree merchants and run API calls as if you were that merchant. Braintree Marketplace allows you to onboard new merchants via our API (as opposed to using our onboarding flow) and allows you to share in a portion of the revenue of the transactions that are run on behalf of your merchants. 

Our Marketplace product provides an API interface to collect details about onboarded merchants via the [Merchant Account](https://developers.braintreepayments.com/reference/response/merchant-account/ruby) object. And our Auth Product does not provide this feature at this time. Braintree Auth is currently in closed beta, and you will need to reach out to auth@braintreepayments.com to enable it.

Feel free to reopen this issue if it does not fully answer your question.

Thanks!

**Comment by shkarlat** [comment]
@pblesi Thanks a lot for your help! This clarifies a lot.
