### ISSUE TITLE
Subscription/Transaction/Customers can't be searched by created/update dates

### ISSUE THREAD

**Issue by thatandyrose** [braintree/braintree_ruby#125]
Currently it's impossible to page for latest subscription from the API without being able to do a `range` search on the created_at/updated_at fields.

This would make paging from API infinitely easier!

The same applies to Transactions and Customers, but for updated_at dates only.

**Comment by mtmarsh3** [comment]
Hi @thatandyrose,

Thanks for the suggestions. You'll be happy to know that we are working on adding `created_at` as an attribute for a `range` search for `Subscriptions` and will have the feature added in a following update!

As far as using `updated_at` in `range` search for `Transactions`, `Subscriptions`, and`Customers`, we don't have this functionality currently. That feature has been requested in the past, and we are still considering it for future updates. However, we have not added it yet as it doesn't give indication as to what has changed (the transaction was created, settled, etc). The same goes for `Subscriptions` and `Customers`. For more context on this specifically for `Transactions`, please check out this [issue](https://github.com/braintree/braintree_ruby/issues/101).

**Comment by thatandyrose** [comment]
@mtmarsh3 hey, that's great to hear... woo hoo! 🎈 🎈 what's the best way to keep on top of your production releases?

Thanks for the explanation on updated_at 👍

**Comment by mtmarsh3** [comment]
No problem! The best way to keep on top of changes is to check our `CHANGELOG.rdoc`. All production releases will be documented in there.

**Comment by mtmarsh3** [comment]
I'm going to close this issue now, if you have any other questions or concerns feel free to reopen it!

**Comment by thatandyrose** [comment]
@mtmarsh3 hey again! (sorry you must hate me). I was just reading over your comments on this issue and agree that `updated_at` doesn't give a sense of what has changed.

However... what if you want to simply say

> "give me all subscriptions which have changed in the last 3 days".

Currently you can't do that at all. Having`updated_at` would at least let us implement our own way of checking what has changed no?

The thing about subscriptions is that they're a bit tricky as they can change any time.

For example... transactions will have a natural lifecycle... settled etc.

However.. a subscription could have it's plan_id changed at any time. Also it' price can change at any point. This is because users of Braintree handle upgrades and downgrades in unpredicatable ways.

Sometimes they will cancel and create a new subscription. That's a nice and easy way to track changes.

However sometimes they'll simply change the plan_id and price.

I guess the super clever way of handling this would be for you to change how you allow users to upgrade and downgrade subscriptions... so create very specifc "subscription task objects". That would be IDEAL.

BUT, that's a big change. Until then exposing `updated_at` as a search field would be super useful!

Thanks! :-)
