### ISSUE TITLE
Subscription/Transactions/Customers search can't be ordered

### ISSUE THREAD

**Issue by thatandyrose** [braintree/braintree_ruby#126]
This is also related to paging. Currently it's impossible to order subscriptions/transactions/Customers. The most useful ordering here would be created_at/update_at

**Comment by mtmarsh3** [comment]
Hi @thatandyrose,

Thanks for bringing this up, we're currently looking into this issue and will get back to you soon.

**Comment by mtmarsh3** [comment]
Hey @thatandyrose,

Thanks again for the suggestion. As of now, we have no plans to develop this feature. If we do, we'll update you in the future!

**Comment by thatandyrose** [comment]
@mtmarsh3 :-( cool thanks for the reply. Howcome out of curiosity? Thanks!

**Comment by mtmarsh3** [comment]
In the past, we haven't worked on it as demand hasn't been high enough for the feature. We will certainly keep it in mind!

**Comment by thatandyrose** [comment]
@mtmarsh3 cool thanks!

**Comment by mtmarsh3** [comment]
I'm going to close this issue now, but please feel free to reopen the issue if you have any other questions!
