### ISSUE TITLE
Get invoices, charges, disputes and others

### ISSUE THREAD

**Issue by shkarlat** [braintree/braintree_ruby#128]
I posted a issue before https://github.com/braintree/braintree_ruby/issues/124 on another question. As I mentioned there I code Braintree Auth API in parallel with Stripe Auth. I need to code some defs that receives the arrays of customers, invoices, charges, disputes and subscriptions. I have found customer.all.ids which has suited me in some way. And subscriptions(subscription), but not .all method that I need or something like it. Maybe there are some similar fields, but are called differently.

I use Braintree Auth and this doc https://developers.braintreepayments.com/guides/braintree-auth/reference/ruby.

And can I find out the place suitable for such questions, because I understand that Github Issues not for this purpose.

Thanks.

**Comment by mtmarsh3** [comment]
Hi @shkarlat,

In BT Auth, you can call the same methods found [here](https://developers.braintreepayments.com/reference/overview), except replacing the class `Braintree` with your `gateway` object. For example, getting all [`Add_ons`](https://developers.braintreepayments.com/reference/request/add-on/all/ruby) would look like: `gateway.add_on.all()`. 
For subscription, you can get all [subscription objects](https://developers.braintreepayments.com/reference/request/subscription/search/ruby) for a merchant_account in the following way:
```
search_results = gateway.subscription.search do |search|
  search.merchant_account_id.is "merchant_account_id"
end
```

For general questions about Api calls, asking on StackOverflow and tagging the question with `Braintree` is a good place to start. For more specific questions involving integrations, I'd recommend contacting [support](https://www.braintreepayments.com/contact).

**Comment by shkarlat** [comment]
@mtmarsh3 

I do it exactly in this way. It does not answer my question. But Ok, I get it.

**Comment by mtmarsh3** [comment]
@shkarlat 

Sorry, could you restate your question? If you're asking if there's a direct `.all` method to grab all of the different types of objects (`Subscriptions`, `Transactions`, `etc`), there is currently not a way to do this.

**Comment by shkarlat** [comment]
@mtmarsh3 

Exactly it! Thanks for the answer.

**Comment by mtmarsh3** [comment]
Great! I'm going to close this issue now, but feel free to reopen it if you have any other questions.

**Comment by shkarlat** [comment]
Ok. I see.
