### ISSUE TITLE
Customer cannot be inferred from Subscription

### ISSUE THREAD

**Issue by thatandyrose** [braintree/braintree_ruby#129]
Please correct me if I'm wrong... but how does one get which Customer belongs to a Subscription?

At the moment you can do this by looking at the transactions of a subscriptions, and then get the customer from there.

But what if a subscription hasn't got any transactions yet, how do you get the customer from the transaction. Doesn't seem possible at the moment?

**Comment by mtmarsh3** [comment]
Hi @thatandyrose ,

Each `Subscription` object will have a [`payment_method_token` ](https://developers.braintreepayments.com/reference/response/subscription/ruby#payment_method_token). With this, you can search for the related [`Customer`](https://developers.braintreepayments.com/reference/request/customer/search/ruby#payment_method_token) with the following code:
```
collection = Braintree::Customer.search do |search|
  search.payment_method_token.is "payment_method_token"
end
```
The `collection` object will then contain the related `Customer`.

**Comment by mtmarsh3** [comment]
We will close this issue for now, but please feel free to reopen the issue if this does not solve your problem!
