### ISSUE TITLE
CardVerification errorResult does not include any error messages

### ISSUE THREAD

**Issue by mbhnyc** [braintree/braintree_ruby#130]
Hey guys,

We switched over to doing verifications separately from our first payments, and I'm surprised the `CardVerification` results isn't including errors like I would expect.  Shouldn't this errorResult serialize the messages from the gateway just like a transaction error?

Thanks.

**Comment by jdlc** [comment]
Hi @mbhnyc,
Here's a little more information on [credit card verification on the server side](https://developers.braintreepayments.com/guides/credit-cards/server-side/ruby#card-verification), and the documentation for accessing attributes of [credit card verifications](https://developers.braintreepayments.com/reference/response/credit-card-verification/ruby).

Gateway validation errors and failed card verifications are two different things, what are you expecting to see?

**Comment by jackellenberger** [comment]
Hey @mbhnyc,

I'm going to close this issue for now, but feel free to reopen it if you have more information for us.
