### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by nate** [braintree/braintree_ruby#131]
Does this gem follow semantic versioning? I'm upgrading from 2.6.2 to the latest and want to know if I should expect code to break. Thanks!

**Comment by mtmarsh3** [comment]
Hi @nate!

We do follow semantic versioning.  Our current version 2.68.1 should be backwards compatible. However, since your version of 2.6.2 was released in 2011, I'd recommend testing your code after upgrading, just to be sure.

**Comment by nate** [comment]
Ok, thanks!

**Comment by nate** [comment]
Do you have any recommendations for testing the code to confirm? We've stubbed it out in the past but that doesn't exercises the library for changes between versions.
