### ISSUE TITLE
Do you guys accept PRs?

### ISSUE THREAD

**Issue by thatandyrose** [braintree/braintree_ruby#132]
Just wanted to know if you guys are open to PRs?

**Comment by danakatz** [comment]
Hi @thatandyrose, indeed we do! If you see room for improvement, feel free to submit a PR and we'll be happy to review it. If we can accept the change without further testing, we'll merge it here; if it requires more updates or investigation, we can still make the change internally and credit you in the changelog.

Thanks for your interest!
