### ISSUE TITLE
raise_exception_for_status_code can get a message

### ISSUE THREAD

**Issue by dan-ding** [braintree/braintree_ruby#133]
It'd be nice if the Braintree::Http methods call Util.raise_exception_for_status_code with a message of what went wrong, if possible, and not just the http status code.
It's not always clear why something doesn't work out.

**Comment by danakatz** [comment]
Hi @dan-ding,

Our hope is that the error type (e.g. `AuthenticationError`, `NotFoundError`, `ServerError`, etc.) will provide enough information to for you to handle accordingly; we typically don't have more specific information than that. Is there a particular scenario that's unclear?

**Comment by dan-ding** [comment]
Well.... lots. 
AuthenticationError gets thrown when trying to update an Apple Pay payment method, which in talks with support seems isn't allowed with anything besides setting the default option. But how's anyone supposed to know? What could possibly be relayed or taken?

In general, a message or something would be helpful so a decision could be made... If the server isn't telling the client what went wrong, what is the client left to do?
See the problem?

**Comment by dan-ding** [comment]
Or as another example, getting an error raised that is:
Braintree::AuthorizationError: Braintree::AuthorizationError
isn't particularly helpful in deciphering what the problem is. Especially when it's not an authorization issue.

**Comment by danakatz** [comment]
Thanks for elaborating @dan-ding. Could you provide some snippets of the requests you mentioned so that we can try to reproduce these errors?

**Comment by EvanHahn** [comment]
There hasn't been movement on this card in a few months. We're going to close this issue, but feel free to comment or open a new issue if you need to!
