### ISSUE TITLE
Force tls 1.2

### ISSUE THREAD

**Issue by aganov** [braintree/braintree_ruby#135]
On some systems (like Ubuntu 12.04) the defaullt tls version used by `Net::HTTP` is tlsv1 this is causing `Braintree::SSLCertificateError` on `sandbox` and after 31 Jan may break some apps on production too. In order to make it work we should force  `ssl_version` to `TLSv1_2`

```ruby
# /lib/braintree/http.rb L78
if @config.ssl?
  connection.use_ssl = true
  connection.ssl_version = :TLSv1_2
  connection.verify_mode = OpenSSL::SSL::VERIFY_PEER
  connection.ca_file = @config.ca_file
  connection.verify_callback = proc { |preverify_ok, ssl_context| _verify_ssl_certificate(preverify_ok, ssl_context) }
end
```

**Comment by danakatz** [comment]
Hi @aganov, thanks for letting us know about this issue! We're working on a way to make this configurable and will update here when it's available.

**Comment by danakatz** [comment]
Starting in [2.71.0](https://github.com/braintree/braintree_ruby/blob/master/CHANGELOG.rdoc#2710), released today, you can set an explicit SSL version on your Braintree configuration object: 

```ruby
Braintree::Configuration.ssl_version = :TLSv1_2
```

We appreciate your patience! Let us know if you run into any other issues.
