### ISSUE TITLE
Braintree Auth and webhook notifications

### ISSUE THREAD

**Issue by polimorfico** [braintree/braintree_ruby#136]
We're using Braintree Auth. Every time we get a notification from Braintree and we try to parse the load, we get the error message: `no matching public key`

However we only have our user access token, not any public or private key. How we can process notifications from our users accounts? Is it possible to do it with Braintree Auth?

**Comment by danakatz** [comment]
Hi @polimorfico, I'd suggest reaching out to [Braintree support](mailto:support@braintreepayments.com) for questions about your account! They'll be able to help with the specifics of your integration.
