### ISSUE TITLE
CustomerSearch result comes in random order

### ISSUE THREAD

**Issue by thatandyrose** [braintree/braintree_ruby#138]
I'm not 100% sure it is random BUT it's definitely not in `:created_at` order. Here's what happend:

1. I search for customers in the Braintree API.
2. I got a 10,000 dataset back.
3. I looped through the return object, saved the model to my DB and stored the `created_at` in a local var as a looped in the order the results came in.
4. When I was finished looping, the last data in the var was: `Sat, 14 Jun 2014 05:06:38 UTC +00:00`
5. I then queried my db and found that the earliest `created_at` date for customers was actually `Wed, 06 Nov 2013 11:44:14 UTC +00:00`

So, the result is not coming in the created_at order. So what order is it coming in?

Also, the order is quite important is it allows me to page the data as you have a 10,000 limit on your API.

Lastly the order NEEDS to be on `created_at` since that's the only range field you allow customers to be searched on. If your order is on anything else then it's impossible to page (not impossible, but very very costly)

cheers!

**Comment by jaypatel512** [comment]
Hey @thatandyrose. Search results don't come in a guaranteed order in sandbox. We do send ordered results in production.

We will close this issue for now. Please re-open if you see the same issue in production.

**Comment by thatandyrose** [comment]
Hi @jaypatel512 :-) This original query was actually about production, not sandbox. So, you DO send results ordered in production, for user? What's it ordered by?

thanks so much

Andy

**Comment by jaypatel512** [comment]
Interesting, as far as our conversation with the specific team working on this, they never updated production with the bug that introduced unordered list result. When you get a list of results back from a query in production, the first element is always the most recently created object (transaction, subscription, etc.).

We are working on updating the docs pretty soon with a similar message.
