### ISSUE TITLE
Master Merchant Account Returns Nil currency_iso_code

### ISSUE THREAD

**Issue by HassanAkbar** [braintree/braintree_ruby#144]
I was trying to play with the currency_iso_code for Braintree. I found out that currency_iso_code is returned 'nil' if the account is 'Master Merchant Account'. It looks like an API bug, however, is there any workaround to this problem
`
@braintree_gateway.merchant_account.find("AccountID").currency_iso_code
`

**Comment by lkorth** [comment]
The API should be returning `currency_iso_code` for master merchant accounts. There is [an integration test](https://github.com/braintree/braintree_ruby/blob/a77ae6125a3271542658fde4eccad6eeac54145a/spec/integration/braintree/merchant_account_spec.rb#L310) that ensures it is returned and parsed. 

Have you ensured the merchant account you're looking up is a master merchant account and has a currency iso code in the control panel?

**Comment by crookedneighbor** [comment]
@HassanAkbar Since we haven't heard back from you, I'm going to close this issue. Please comment here if you're still experiencing issues.
