### ISSUE TITLE
stupid question

### ISSUE THREAD

**Issue by justinemar** [braintree/braintree_ruby#146]
Stupid question... are the credentials different from 
https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/testing-go-live/ruby/ which support philippines

**Comment by bluk** [comment]
The credentials are different for this SDK if your merchant account is with Braintree versus `Express Checkout with Braintree SDK`. Both solutions use the same SDK but the setup is slightly different. Express Checkout with Braintree SDK [supports the Philippines](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/countries/) for taking PayPal payments.

If you are using Express Checkout with Braintree SDKs, you can follow the [instructions here](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/testing-go-live/ruby/#live-configuration). You will need to [get an access token](https://www.paypal.com/businessexp/api/accesstoken). Please ensure that you construct the `Braintree::Gateway` with the access token as [described here](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/server-side/ruby/#construct-your-gateway-object).

Note if your account is with Braintree, you can follow the [developer docs here](https://developers.braintreepayments.com/start/overview).

Hope that helps! If you have additional questions, please feel free to leave a comment or contact [PayPal Support](https://developer.paypal.com/support/) for Express Checkout or account related questions.
