### ISSUE TITLE
Reading merchant accounts with a "read_only" scope fails

### ISSUE THREAD

**Issue by lkdjiin** [braintree/braintree_ruby#147]
### General information

* SDK/Library version: 2.78.0
* Environment: sandbox

### Issue description

When I want **to read** merchant accounts like this:

```ruby
result = gateway.merchant_account.all
result.merchant_accounts.each do |account|
  puts account.id
end
```

If the Oauth scope is read only (`:scope => "read_only"`) it fails with `Braintree::AuthorizationError`.

But if the scope is read and write (`:scope => "read_write"`) it works well.

It seems like a bug to me.

**Comment by crookedneighbor** [comment]
Thanks for the report. We'll get this fixed.

**Comment by ThatHurleyGuy** [comment]
We just deployed a fix for this. Let me know if you're still having any problems here.
