### ISSUE TITLE
[Request] Add option to suppress logs, or suppress them automatically for test environment

### ISSUE THREAD

**Issue by badosu** [braintree/braintree_ruby#149]
This is an undocumented issue that is very difficult to diagnose and discover where it's coming from: https://github.com/braintree/braintree_ruby/issues/38

To fix this we have to use the undocumented workaround for the issue aforementioned.

It would make a lot of sense to expose this option so that we have a standard way to deal with this, or choose better defaults for each environment, since this seems like a big benefit just for production, staging or debugging on development. For all other cases it introduces noise on the tests and development environments.

If any of these options is not possible, at least document this on the TESTS section so that other developers already have a reference on how to deal with this.

**Comment by crookedneighbor** [comment]
Would you like to open a PR to add that note to the README?

**Comment by badosu** [comment]
👍
