### ISSUE TITLE
Default rake command

### ISSUE THREAD

**Issue by cdpalmer** [braintree/braintree_ruby#155]
### General information

Inconsistencies with `Rakefile` and `PULL_REQUEST_TEMPLATE`

### Issue description

`.github/PULL_REQUEST_TEMPLATE.md` says to run the unit tests, just simply run `rake`.
But the `Rakefile` default is set to: `task :default => "test:all"`, which will run all the integration specs as well, which won't work unless you have the development servers mentioned in the README

**Comment by cdpalmer** [comment]
My guess is we just change the `PULL_REQUEST_TEMPLATE` to say simply run `rake test:unit`

**Comment by crookedneighbor** [comment]
:+1: Feel free to PR it

**Comment by cdpalmer** [comment]
Closing issue after PR: https://github.com/braintree/braintree_ruby/pull/156
