### ISSUE TITLE
Huge memory bloat when iterating subscriptions

### ISSUE THREAD

**Issue by yassenb** [braintree/braintree_ruby#159]
### General information

* SDK/Library version: 2.80.1
* Environment: both production and sandbox
* Language, language version, and OS: Ruby 2.5.0 (also tested on 2.3.1) on Ubuntu 16.04

### Issue description

Iterating over all subscriptions with `Braintree::Subscription.search.each` causes a huge memory bloat (hundreds of megabytes). There are three main issues I've noticed here:
* You can't specify page size, the value returned from the API is used - https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/resource_collection.rb#L9
* The XML returned from the API is huge - over 2MiB for 20 subscriptions. The page size returned from the API seems to vary between 50 and 100 so it means over 10MiB
* The parsing of megabytes of XML causes the memory to bloat drastically (switching to libxml alleviates the issue but only to some extent) but it's not only that. The subsequent transformations of the hash allocate even more objects, effectively copying the hash several times over - https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/xml/parser.rb#L14-L19

**Comment by crookedneighbor** [comment]
Thanks for bringing this up. 

We'll do some investigating into this as we have time. If you'd like to speed the process along, pull requests are welcome!

**Comment by theasteve** [comment]
Hi @crookedneighbor, is a PR for this issue still welcome? Would love to work on it

**Comment by crookedneighbor** [comment]
Yes. Feel free to open a PR.

**Comment by hollabaq86** [comment]
👋  Version 3.0.1 includes some refactoring to address the third point in this issue specifically about XML parsing. We did see improvements in memory allocation, so we're going to go ahead and close this issue. If there's any additional issues, please go ahead and open a new issue and we'll take a look.
