### ISSUE TITLE
Search: first does not return the most recent record

### ISSUE THREAD

**Issue by bgitt** [braintree/braintree_ruby#160]
### General information

* SDK/Library version: 2.78.0
* Environment: Production and Sandbox
* Language, language version, and OS: ruby 2.3.5, Ubuntu 14.04

### Issue description

When doing a customer search (`Braintree::Customer.search`), calling `first` on the result returns a random record instead of the most recently created one. 

From the [Braintree Search Docs](https://developers.braintreepayments.com/reference/general/searching/search-results/ruby):
>When you get a list of results back from a query in production, the first element is always the most recently created object (transaction, subscription, etc.).
>
>Search results include Enumerable so you can iterate over them using each or any method [defined in Enumerable](http://ruby-doc.org/core-2.5.0/Enumerable.html).

Example: 
```ruby
70:(main)> result = Braintree::Customer.search do |search|
        >>   search.email.is email
        >> end
=> #<Braintree::ResourceCollection:0x00007fa7b7f139f0
 @ids=
  ["164912544",
   "470306696",
   "501866894",
   "576958016",
   "591616571",
   "633680401",
   "647416203",
   "657212396",
   "689832783",
   "693752121",
   "837879036",
   "847053639",
   "862670099",
   "871403181"],
 @page_size=50,
 @paging_block=
  #<Proc:0x00007fa7b7f139a0@/home/vagrant/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/braintree-2.78.0/lib/braintree/customer_gateway.rb:49>>
71:(main)> result.first.id == result.to_a.first.id
=> false
72:(main)> result.first.id
=> "164912544"
73:(main)> result.to_a.first.id
=> "657212396"
```

**Comment by bluk** [comment]
The ordering is not guaranteed for the results. The search docs will be updated. If you need any help, feel free to contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) or leave a comment.
