### ISSUE TITLE
Multi-tenancy support / dynamically set Braintree configuration (merchant id, public/private keys)?

### ISSUE THREAD

**Issue by gregblass** [braintree/braintree_ruby#163]
I'm currently setting my Braintree merchant_id and public/private keys in a 'braintree.rb' file in config/initializers:

`Braintree::Configuration.merchant_id = Rails.application.secrets.braintree_merchant_id
Braintree::Configuration.public_key = Rails.application.secrets.braintree_public_key
Braintree::Configuration.private_key = Rails.application.secrets.braintree_private_key`

This works fine for a single-tenant application. For multi-tenancy, I'm storing this data in the database (with the private key encrypted), like a couple of other integrations my software uses. For example, for Mailgun, I'm setting the account specific info (API Key, etc) dynamically when sending mail.

Is there any way to dynamically set the Braintree configuration keys instead of setting it once/application wide/in an initializer?

**Comment by gregblass** [comment]
Looks like this was already asked here: https://github.com/braintree/braintree_ruby/issues/123, and that the recommended method is using Braintree Auth.

**Comment by crookedneighbor** [comment]
The [documentation](https://developers.braintreepayments.com/start/hello-server/ruby#install-and-configure) has been updated recently to create Gateway instances instead of universally setting the API keys. 

```ruby
gateway = Braintree::Gateway.new(
  :environment => :sandbox,
  :merchant_id => "use_your_merchant_id",
  :public_key => "use_your_public_key",
  :private_key => "use_your_private_key",
)
```

Braintree Auth requires this pattern to work, but you don't necessarily need to be using Braintree Auth to make a gateway instance.
