### ISSUE TITLE
Sudden Braintree::SSLCertificateError 

### ISSUE THREAD

**Issue by erhanberber** [braintree/braintree_ruby#165]
### General information

* SDK/Library version: 2.56.0
* Environment: Production
* Language, language version, and OS: Ruby 1.9, Rails 3.1

### Issue description

Starting past few days, probably at around June 25th we started getting Braintree::SSLCertificateError error in our procure action.  Nothing changed on the app, or on the server, same ssl certificates are still installed on our server.

What could be causing this sudden error?

This is our production box, we will appreciate your prompt response.  Thank you.

Erhan Berber

**Comment by quinnjn** [comment]
Hi @erhanberber,

PCI compliance requires Braintree to support TLS >= 1.2 going forward. In one of the [blog posts about the TLS 1.2 upgrade](https://www.braintreepayments.com/blog/updating-your-production-environment-to-support-tlsv1-2/) we listed server SDKs that will be affected.

Here is the [Ruby upgrade section](https://github.com/paypal/TLS-update#ruby)

In that upgrade section it lists Ruby 2.0.0 as the minimum Ruby version for TLS 1.2. You had listed Ruby 1.9 as your language version. 

This may not be the only change you need to make to prepare for TLS 1.2 but its a first step!

If you have more questions about the TLS 1.2 upgrade you're better off opening a [support ticket](https://www.braintreepayments.com/contact) and they can look more into your account and what steps you may need to complete!
