### ISSUE TITLE
Not updating default payment method for customer - gateway_rejected

### ISSUE THREAD

**Issue by ravindra9278** [braintree/braintree_ruby#176]
### Braintree not updating default payment method for user  (I am managing multiple cards for single user)

* A user can save multiple cards in his vault.
* Right now I have set `X` card is default card.
* Now when I trying to update default card `X` to  card `Y` then getting below error.

```
def set_default_card(customer_id, card_token)
   result = braintree_gateway.customer.update!(
      customer_id,
      default_payment_method_token: card_token
    )
end
```
Getting below error response from Braintree

`
#<Braintree::ErrorResult params:{...} errors:<> credit_card_verification: #<Braintree::CreditCardVerification status: "gateway_rejected", processor_response_code: "1000", processor_response_text: "Approved", amount: "0.0", currency_iso_code: "USD", cvv_response_code: "I", avs_error_response_code: nil, avs_postal_code_response_code: "M", avs_street_address_response_code: "I", merchant_account_id: "", gateway_rejection_reason: "cvv", id: "jhaxpe3x", credit_card: {:token=>"9hzn8f", :bin=>"555555", :last_4=>"4444", :card_type=>"MasterCard", :expiration_month=>"07", :expiration_year=>"2020", :customer_location=>"US", :cardholder_name=>nil, :unique_number_identifier=>"08fcca8ebeb23f94e7da2131cc2c8900", :account_type=>nil, :global_id=>"cGF5bWVudG1ldGhvZF85aHpuOGY", :prepaid=>"Unknown", :healthcare=>"Unknown", :debit=>"Unknown", :durbin_regulated=>"Unknown", :commercial=>"Unknown", :payroll=>"Unknown", :issuing_bank=>"Unknown", :country_of_issuance=>"Unknown", :product_id=>"Unknown"}, billing: {:first_name=>nil, :last_name=>nil, :company=>nil, :street_address=>nil, :extended_address=>nil, :locality=>nil, :region=>nil, :postal_code=>"12345", :country_name=>nil}, created_at: 2019-04-11 05:49:00 UTC>>
`

Please guide me if I am doing wrong.

**Comment by crookedneighbor** [comment]
Please reach out to our support team for help with this. They'll be able to check the settings on your account to see if anything is causing this.

https://help.braintreepayments.com/
