### ISSUE TITLE
Does Braintree has referral feature? 

### ISSUE THREAD

**Issue by tenzil-rpx** [braintree/braintree_ruby#177]
I use braintree in production in one of our application, We are looking forward to have referral system in our app, where user gets benefits on referring someone. Does braintree already have referrals functionality.  
if not, is it in upcoming roadmaps?

**Comment by hollabaq86** [comment]
Hi @tenzil-rpx, please [contact Support](https://help.braintreepayments.com/) who can assist you with your question.
