### ISSUE TITLE
Testing with linked paypal sandbox

### ISSUE THREAD

**Issue by sl0thentr0py** [braintree/braintree_ruby#178]
### General information

* SDK/Library version: Example: 2.94.0
* Environment: Sandbox 
* Ruby 2.3.7, Arch Linux

### Issue description

Our tests use the `fake-paypal-billing-agreement-nonce` to test the paypal flow. When we create a payment method with this nonce, it returns the following response with email `jane.doe@paypal.com`.

```
{:paypal_account=>
  {:billing_agreement_id=>"paypal_billing_agreement_id",
   :created_at=>2019-05-06 11:29:34 UTC,
   :customer_id=>"GFLBEANSCQVUHMWR_u_1",
   :default=>true,
   :email=>"jane.doe@paypal.com",
   :global_id=>"cGF5bWVudG1ldGhvZF9wcF9mODdycWs",
   :image_url=>"https://assets.braintreegateway.com/payment_method_logo/paypal.png?environment=sandbox",
   :subscriptions=>[],
   :token=>"f87rqk",
   :updated_at=>2019-05-06 11:29:34 UTC,
   :is_channel_initiated=>false,
   :payer_id=>nil,
   :payer_info=>nil,
   :limited_use_order_id=>nil}}
```

We then make a `Transaction.sale` with this token.
This used to work with the mocked sandbox flow, but after linking an actual paypal sandbox, it fails with a decline code of `2073`.

 I'm guessing that's because there's no sandbox buyer with that email. Can anyone help me on how I can resolve this and test with a linked paypal sandbox?

**Comment by hollabaq86** [comment]
Hi @sl0thentr0py, the `fake-paypal-billing-agreement-nonce` can't be used with a linked PayPal sandbox account, it can only be used with the mocked PayPal flow. For assistance getting your tests to pass, please [contact Support](https://help.braintreepayments.com/).
