### ISSUE TITLE
Custom Fields for Transactions via Subscriptions?

### ISSUE THREAD

**Issue by jpemberthy** [braintree/braintree_ruby#18]
Hey guys, 

According to these [docs](http://www.braintreepayments.com/docs/ruby/general/custom_fields) _custom fields can be associated with newly created transactions or customer vault records_. So I'm wondering how should I pass the custom fields for a transaction that's being created via a subscription#create operation, seems like `Braintree::Subscription.create` doesn't support the `:custom_fields` option and based in the docs it makes sense for me, but then how should achieve this? any help would be really appreciated!

**Comment by kirillgroshkov** [comment]
+1, I need a feature to set customFields when creating Subscription

**Comment by elvizcacho** [comment]
+1 👍

**Comment by Connum** [comment]
7 years have passed and this has not been implemented yet... There are so many use cases for this... In my case I'd like to pass a description text for invoicing (which happens by querying transactions via a cronjob).

**Comment by hamzabinamin** [comment]
Is there any update on this?  Its really sad to know that 9 years later we still can't achieve this.

**Comment by robjbrain** [comment]
Also can't believe its been more than a decade without this basic feature..

It seems like the work around might be to add custom fields to the customer, but it does seem crazy that the webhooks send subscription info with 0 way to relate that back to a specific order within our own systems.

**Comment by lukasvarkalis** [comment]
This question is still relevant! There is no official documentation on how recurring payments should be handled and matched with subscriptions at the moment.
I think it would be fair to reopen this issue.

@hollabaq86 Might you can help with this question? 🤞

**Comment by hollabaq86** [comment]
Hey folks, I’m locking this issue down. That said, please know that I am forwarding on all your feedback to the relevant product teams so they can evaluate whether or not to add support for custom fields to subscriptions. 

I can’t guarantee it will get added or what the ETA for that to be available to use should we add this feature, but it _is_ getting forwarded to the responsible parties to make that decision. 

Going forward, if there is a feature that you are really passionate about, please [contact Technical Support](https://developer.paypal.com/braintree/help/). Engineering teams coordinate with our colleagues in Support on the regular, including getting feedback/feature requests!
