### ISSUE TITLE
Customer Create API error with make_default options

### ISSUE THREAD

**Issue by thinhhuynh** [braintree/braintree_ruby#180]
### General information

* SDK/Library version: 2.95.0
* Environment: sanbox
* Ruby on Rail, Ruby 2.5, Rails 5.2, and OS: macos

### Issue Create Customer Error with make_default option

I call gateway to create customer like below

`result = gateway.customer.create(
          id: '1234567890',
          company: "test company",
          payment_method_nonce: params[:nonce],
          options: {
            make_default: true
          }
        )`
then I get error

`invalid keys: options[make_default]`

Creating customer was successful without options parameter

Thanks

**Comment by Epreuve** [comment]
`options` is nested inside `credit_card`, not on the root `customer`.  Change it to 
```
credit_card: { 
  options: { 
    make_default: true
  }
}
```
And you should stop receiving the error.  You can refer to the docs [here](https://developers.braintreepayments.com/reference/request/customer/create/ruby#credit_card.options), or reach out to [support](https://help.braintreepayments.com/) with any other question.
