### ISSUE TITLE
Missing bin accessor in Braintree::Transaction::ApplePayDetails

### ISSUE THREAD

**Issue by demchukilya** [braintree/braintree_ruby#190]
### General information

* SDK/Library version:  2.98.0
* Environment: Sandbox
* Language, language version, and OS: Ruby 2.3.8p459 on Ubuntu 16.10

### Issue description
It looks like attribute reader to "bin" field Braintree::Transaction::ApplePayDetails is missing.
This filed is described in documentation and I can see this data in a object, but can't get access to it without workarounds.

**Comment by Epreuve** [comment]
@demchukilya Sure looks to be missing, good call out.  I did a quick spot check and I think that's the only one that looks to be missing there.  We will want to do a double check of the other `details` classes as well, but this should be a relatively quick fix to add the reader.  If you have the time to PR it, even quicker still.

**Comment by hollabaq86** [comment]
Hi @demchukilya this got added to version 2.100.0. Could I trouble you to update the version you're using and let us know if you continue to encounter this issue?

**Comment by crookedneighbor** [comment]
Gonna close this, but we can re-open it if you're still having issues accessing it.
