### ISSUE TITLE
gateway.subscription.create gives ArgumentError

### ISSUE THREAD

**Issue by pbenkoe** [braintree/braintree_ruby#196]
### General information

* SDK/Library version: 2.101.0
* Environment: Sandbox
* Language, language version, and OS: Ruby 2.6.5, Rails 6.0.2.1

### Issue description

`gateway.subscription.create` fails with "invalid keys: payment_method_token" error message.
e.g. `gateway.customer.create` is successful, so the gateway is set up correctly.

```ruby
def subscribe(payment_token, plan_id)
  result = gateway.subscription.create(
    payment_method_token: payment_token,
    plan_id: plan_id
  )

  if result.success? || result.transaction
    redirect_to new_subscription_path(result.transaction.id)
  else
    flash_error(result.error_message)
  end
end
```

Logs:
```
ArgumentError (invalid keys: payment_method_token[payment_token]):
  
app/controllers/subscriptions_controller.rb:49:in `subscribe'
app/controllers/subscriptions_controller.rb:24:in `create'
```

I was following the docs and example code from here:
https://developers.braintreepayments.com/reference/request/subscription/create/ruby

**Comment by hollabaq86** [comment]
👋 @pbenkoe, please [contact Support](https://help.braintreepayments.com/) with your merchant ID and the payment method token you were attempting to include in your subscription.create call, they'll be able to assist you in troubleshooting.
