### ISSUE TITLE
submit_for_partial_settlement transaction method crashes

### ISSUE THREAD

**Issue by AhmedSalahKhodair** [braintree/braintree_ruby#199]
* Gem version:  braintree (2.102.0)
* Environment: Sandbox
* Rails 5.2.4.1
* ruby 2.5.7
* Ubuntu 18.04

### Issue description

I created 'Authorized' transaction using some customer's payment method (which was of Credit Card type)
Now, I'm trying to capture part of it using `submit_for_partial_settlement` method:

> `gateway.transaction.submit_for_partial_settlement(transaction_id, amount)`

But it crashes giving:

> **Braintree::AuthorizationError: Braintree::AuthorizationError**
> **from /home/ahmedsalah/.rvm/gems/ruby-2.5.7/gems/braintree-2.102.0/lib/braintree/util.rb:53:in `raise_exception_for_status_code'**

**Comment by hollabaq86** [comment]
👋 Please [contact Support](https://help.braintreepayments.com/) who can help troubleshoot the issue with you. The exception [AuthorizationErrror](https://developers.braintreepayments.com/reference/general/exceptions/ruby#authorization-error) indicates there is an issue with your API keys or the data that was sent was malformed.
