### ISSUE TITLE
The transaction object passed in through the webhook on disputes does not have "created_at" 

### ISSUE THREAD

**Issue by Fjan** [braintree/braintree_ruby#200]
### General information

* SDK/Library version: 2.102.0
* Environment: Production
* Language, language version, and OS: Ruby 2.6.3, Mac OS

### Issue description

According to the documentation (1) a Dispute passed in through a webhook should contain the Transaction with a "created_at" field. However, although we can access most fields of the Dispute and the Transaction, it seems the created_at field is missing in the gem. 

When I decrypt and log the webhook I see the "created-at" value is present in the XML being sent, so it's probably missing an accessor. It would be very useful for us if we could actually read that information through the gem.

(1) https://developers.braintreepayments.com/reference/response/dispute/ruby

**Comment by scannillo** [comment]
The `created_at` attribute is available on the `evidence` property for Disputes. Example: `disputeResult.evidence.created_at`.

On the `Transaction`, the `created_at` attribute is available top-level https://developers.braintreepayments.com/reference/response/transaction/ruby#created_at.

**Comment by Fjan** [comment]
@scannillo Why did you close this? 

The documentation linked in the issue clearly shows the created_at should be available on the transaction, so at a minimum the documentation should be fixed if you believe the missing created_at behaviour is correct. 

I understand I can do another call to get the Transaction object and read the created_at value from there, but that's just a kludge since the value is already available in the Dispute. Simply updating the gem to add the accessor to read the created_at value should not be too hard.

**Comment by scannillo** [comment]
Hi @Fjan. You should be able to access `created_at` as a top level attribute on both `Dispute` and `Transaction`. You can see them set as accessors [here](https://github.com/braintree/braintree_ruby/blob/24feda554da07765b4df578d8c88dbab30b6f80a/lib/braintree/dispute.rb#L10) and [here](https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/transaction.rb#L107).

Reaching out to our Support team will be your best bet (www.help.braintreepayments.com) where they can inspect the webhook and troubleshoot your specific integration.

**Comment by crookedneighbor** [comment]
I do know that the first iteration of dispute webhooks did not include a created_at field for transactions, you can see that here in the sample webhooks for old disputes: https://github.com/braintree/braintree_ruby/blob/24feda554da07765b4df578d8c88dbab30b6f80a/lib/braintree/webhook_testing_gateway.rb#L353-L356

But the current disputes being sent should include the created_at field: https://github.com/braintree/braintree_ruby/blob/24feda554da07765b4df578d8c88dbab30b6f80a/lib/braintree/webhook_testing_gateway.rb#L771

**Comment by Fjan** [comment]
@crookedneighbor Yes, the created at is indeed present on the webhook, this bug report is because it’s not accessible through the ruby gem. 
So dispute.transaction.created_at raises an exception, you need to retrieve the Transaction object again to get the created_at. 

@scannillo Should I interpret this as won’t fix? Can you please update the documentation in that case to remove the created at?

**Comment by crookedneighbor** [comment]
It _should_ be accessible via the gem. 

Here is where the dispute object is created on the webhook notification: https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/webhook_notification.rb#L94

Here is where the transaction object is created on the dispute object: https://github.com/braintree/braintree_ruby/blob/24feda554da07765b4df578d8c88dbab30b6f80a/lib/braintree/dispute.rb#L118

And here is the `created_at` accessor on the transaction object: https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/transaction.rb#L107

So as far as I can tell, it should _just work_. 

I'm going to re-open this issue, but we still recommend to contact our support team so we can look up the webhooks in question on our end.

**Comment by Fjan** [comment]
@crookedneighbor Thank you very much for looking into this. I agree that it looks like it should work. But I do notice that the unit test for the dispute ominously test all attributes, except created_at...

https://github.com/braintree/braintree_ruby/blob/24feda554da07765b4df578d8c88dbab30b6f80a/spec/unit/braintree/dispute_spec.rb#L317

I'm travelling and am not able to easily run the test suite here, can you please complete that test to see if it works? Adding this line should do it:
`dispute.transaction.created_at.should == Time.utc(2009, 2, 9, 12, 59, 59)`

On my end I'm simply calling `dispute.transaction.amount`, which works fine, and then `dispute.transaction.created_at` which fails.

**Comment by Fjan** [comment]
@crookedneighbor I see the problem, the Dispute does **not** create a Transaction object, it creates a Dispute:Transaction object. As you can see that object is indeed missing the created_at accessor:
https://github.com/braintree/braintree_ruby/blob/24feda554da07765b4df578d8c88dbab30b6f80a/lib/braintree/dispute/transaction.rb#L3

**Comment by crookedneighbor** [comment]
Wow, that's very strange. We'll take a look into it.

**Comment by crookedneighbor** [comment]
I'm checking with the disputes team about if there's a special reason for it to be it's own dedicated class instead of the regular Transaction class, but regardless, we'll definitely get this added and fixed up.

**Comment by crookedneighbor** [comment]
`created_at` is now available in v2.103.0

**Comment by mohamedhafez** [comment]
It would be great if `created_at` returned a `Time` object instead of a `String`, but I guess that's a breaking change at this point?
