### ISSUE TITLE
 undefined local variable or method `nonce_from_the_client' for main:Object (NameError)

### ISSUE THREAD

**Issue by kul1** [braintree/braintree_ruby#204]
### General information

* SDK/Library version: 3.0.1
* Environment: Quick Start Example 
* Language, language version, and OS: ruby 2.6.3

### Issue description

 undefined local variable or method `nonce_from_the_client' for main:Object (NameError)

### Step to create error:

1. Follow instruction from README.md 
https://github.com/braintree/braintree_ruby/blob/master/README.md
2. Repalce "your_merchant_id", "your_public_key", "your_private_key" with parameter  from sandbox registered.
3. Run: ruby quickstart.rb
4. Result
```
Traceback (most recent call last):
quickstart.rb:14:in `<main>': undefined local variable or method `nonce_from_the_client' for main:Object (NameError)
```

### Question:

What exactly need to do to get success responsed for test from Quick Start Example

**Comment by crookedneighbor** [comment]
You need to replace the `nonce_from_the_client` variable with the payment method nonce from your client integration.

You can also use the string `"fake-valid-nonce"` in sandbox if you do not have a client integration (yet!).

**Comment by kul1** [comment]
Thanks it worked,
Should it be noted in README
