### ISSUE TITLE
Migrate from libxml-ruby to nokogiri

### ISSUE THREAD

**Issue by mohamedhafez** [braintree/braintree_ruby#205]
Making libxml-ruby a hard requirement in version 3.x.x has made this gem incompatible with JRuby, replacing the libxml-ruby gem with nokogiri would restore that compatibility. libxml-ruby and nokogiri both rely on a bundled libxml2 version 2.9.10 C-extension under the hood for regular Ruby, so there shouldn't be any impact there.

Even for regular Ruby users, since nokogiri is already a dependency of Rails (through actiontext), there would be the added benefit of not having an extra dependency pulled in in most cases.

**Comment by crookedneighbor** [comment]
Thanks for the suggestion, we're discussing it internally.

**Comment by headius** [comment]
We JRuby maintainers would love to see this happen! If we can help in some way let us know. Nokogiri works well on JRuby and we would love to be able to say we support Braintree.
