### ISSUE TITLE
Use a generic HTTP library like Faraday

### ISSUE THREAD

**Issue by singpolyma** [braintree/braintree_ruby#212]
It would be very nice if the gem used a library like Faraday with swappable HTTP backends so that it could be used properly in an EventMachine environment, for example.

**Comment by sestevens** [comment]
Hi @singpolyma, this isn't something we have on our roadmap right now, but we can leave this issue open to gauge interest in something like this.

**Comment by DPoplin** [comment]
Closing this due to lack of further response.
