### ISSUE TITLE
Wrong error code constants

### ISSUE THREAD

**Issue by shaunma** [braintree/braintree_ruby#213]
[Error codes](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby#code-93107) 93106 and 93107's constant names are flipped.

https://github.com/braintree/braintree_ruby/blob/fa974389eddb9f5b8f414f88e226f4868b4921e7/lib/braintree/error_codes.rb#L712

https://github.com/braintree/braintree_ruby/blob/fa974389eddb9f5b8f414f88e226f4868b4921e7/lib/braintree/error_codes.rb#L706

PaymentMethodNonceConsumed should be 93107
CannotForwardPaymentMethodType should be 93106

**Comment by scannillo** [comment]
Hi @shaunma - thank you for catching this. You are correct! We will get this cleared up in the Ruby SDK.

**Comment by Body87** [comment]
> [](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby#code-93107)Имена постојаних [кодова грешака](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby#code-93107) 93106 и 93107 се преокрећу.
> 
> https://github.com/braintree/braintree_ruby/blob/fa974389eddb9f5b8f414f88e226f4868b4921e7/lib/braintree/error_codes.rb#L712
> 
> https://github.com/braintree/braintree_ruby/blob/fa974389eddb9f5b8f414f88e226f4868b4921e7/lib/braintree/error_codes.rb#L706
> 
> ПаиментМетходНонцеЦонсумед треба да буде 93107
> ЦаннотФорвардПаиментМетходТипе треба да буде 93106

**Comment by scannillo** [comment]
👋  Hello @Body87  - we released a fix for this in[ Braintree Ruby v4.1.0](https://github.com/braintree/braintree_ruby/blob/master/CHANGELOG.md#410). Thank you for opening the issue!
