### ISSUE TITLE
Add customer_id to Subscription fields

### ISSUE THREAD

**Issue by key88sf** [braintree/braintree_ruby#221]
### General information

* SDK/Library version: 4.4.0
* Environment: Production + Sandbox
* Language, language version, and OS: All languages

### Issue description

Please add the `customer_id` field to the top level fields on the Subscription object.

**Comment by crookedneighbor** [comment]
You can use the [payment method find method](https://developer.paypal.com/braintree/docs/reference/request/payment-method/find) with the [payment method token param](https://developer.paypal.com/braintree/docs/reference/response/subscription#payment_method_token) to get the object representing the underlying payment method for the subscription. That includes the [customer id](https://developer.paypal.com/braintree/docs/reference/response/credit-card#customer_id).

If you'd still like the customer id on the top level of the Subscription object, please pass along that feature request to our support team. https://developer.paypal.com/braintree/help

**Comment by key88sf** [comment]
Yes, I would like that at the top level. I'll try contacting the support team (though I think that will not go anywhere, but we'll see).
