### ISSUE TITLE
The client does not handle uncompressed http response

### ISSUE THREAD

**Issue by mengzhou-instacart** [braintree/braintree_ruby#222]
### General information

* SDK/Library version: 4.5.0
* Environment: both sandbox and production
* Language, language version, and OS: Ruby, all versions, cross-platform.

### Issue description

When the http response is uncompressed (Content-Encoding header is not set), [the client simply ignores the response.body](https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/http.rb#L172-L181). This behaviour cases NPE when the client parses the result.

**Comment by hollabaq86** [comment]
👋  @mengzhou-instacart what type calls are you making that are resulting in this header not being set?

**Comment by hollabaq86** [comment]
I've forward your feedback to our engineering teams because we should have uniform headers for our responses. We prefer to fix this issue on the server side rather than have the client adjust.

**Comment by hollabaq86** [comment]
On deeper investigation, the only scenario we could find where we weren't including Content-Encoding header were for 204 responses which makes sense [given the HTTP spec](https://www.rfc-editor.org/rfc/rfc7231#page-29).

If anyone does receive a non-204 response that does not include the Content-Encoding header, please [contact Support](https://developer.paypal.com/braintree/help) so we can have the engineering team that owns the API investigate.
