### ISSUE TITLE
Braintree::ConfigurationError when testing LocalPayment Webhooks

### ISSUE THREAD

**Issue by craisp** [braintree/braintree_ruby#225]
### General information

* SDK/Library version: 4.6.0 
* Environment: Sandbox 
* Language, language version, and OS: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

### Issue description

Hello

I want to implement webhooks to accept local payments on a rails website.
Unfortunately I was not able to create a SampleWebhook to test my code:

```
gateway = Braintree::Gateway.new(
  :environment => :sandbox,
  :merchant_id => [filtered],
  :public_key => [filtered],
  :private_key => [filtered],
)

sample_notification = gateway.webhook_testing.sample_notification(
  Braintree::WebhookNotification::Kind::LocalPaymentCompleted,
  "my_id"
)

webhook_notification = gateway.webhook_notification.parse(
  sample_notification[:bt_signature],
  sample_notification[:bt_payload]
)
Braintree::ConfigurationError (Braintree::Configuration.environment needs to be set)
```
If I create a `SubscriptionWentPastDue` Notification, it works fine.
```
sample_notification = gateway.webhook_testing.sample_notification(
  Braintree::WebhookNotification::Kind::SubscriptionWentPastDue,
  "my_id"
)

webhook_notification = gateway.webhook_notification.parse(
  sample_notification[:bt_signature],
  sample_notification[:bt_payload]
)
=> #<Braintree::WebhookNotification:0x000055e54b4edac8 ...
```

What am I doing wrong?
Thank you very much.

**Comment by hollabaq86** [comment]
👋  @craisp apologies for the delay in a response, can you [contact Braintree Support](https://developer.paypal.com/braintree/help
) referencing this issue and your sandbox merchant ID? They can assist in troubleshooting.
