### ISSUE TITLE
Possible ReDos in the AddressGateway class

### ISSUE THREAD

**Issue by Akash-Karmakar-e3082** [braintree/braintree_ruby#232]
General information

* SDK/Library version: 2.10.0
* Environment: production
* Language, the language version, and OS: ruby-2.3.8

 Issue description
There is a possible ReDos in the regex when a crafted payload is fed:
https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/address_gateway.rb#L16

<img width="755" alt="Screenshot 2023-06-08 at 1 08 55 AM" src="https://github.com/braintree/braintree_ruby/assets/56721980/4b695b84-27a0-4ee4-8988-25ea34a13121">

**Comment by hollabaq86** [comment]
👋 @Akash-Karmakar-e3082 thanks for reaching out. It looks like you're testing in a pretty old version of Ruby and the SDK. Do you encounter the same issue after updating to v3 of the Ruby SDK? 

I'm currently unable to replicate this in a test container that's running Ruby 3.0.1 and the latest version of the SDK

**Comment by Akash-Karmakar-e3082** [comment]
@hollabaq86 I believe, the issue is reproducible only in the lower version of Ruby. From the 3.2 series of Ruby, it provides a built-in timeout handler (https://blog.kiprosh.com/ruby-3-2-0-introduce/), so it won't be an issue for the higher version of ruby.
Can we have a CVE for the lower version, as many applications might be using it?
