### ISSUE TITLE
Create transaction returns 422 in logs but no errors

### ISSUE THREAD

**Issue by acaporrini** [braintree/braintree_ruby#233]
### General information

* SDK/Library version: 4.2.0
* Environment: production
* Language, language version, and OS: Ruby 2.6.7, Gentoo Linux 2.8

### Issue description

Hi all, we use the sdk for our Ruby Braintree integration and we encountered an issue while calling 

```
gateway.transaction.sale(params)
```

In most cases if a transaction fails we are able to check the reasons by checking for example:

```
result = gateway.transaction.sale(
          amount: "100",
          payment_method_nonce: payment_method_nonce,
          transaction_source: :unscheduled,
          customer_id: "CUSTOMER_ID",
          purchase_order_number: "XXX",
          merchant_account_id: "ABCD1234",
          options: { submit_for_settlement: true },
          custom_fields: { custom_field_1: "value"}
)

```

and then calling

```
result.errors
```

However in some cases we see that even tho the transaction doesn't return success, our app doesn't fetch any error from the result. 

Checking the logs I can see:

```
I, [2023-05-28T12:01:22.382646 #15065]  INFO -- : [Braintree] [28/May/2023 12:01:22 UTC] POST /merchants/[merchant_id]/transactions 422
```

And I would like to understand what is the reason of these 422 considering that on a second attempt with same params the transaction is executed. 

So I wanted to ask if in case of 422 there's another type of error handling we should implement to catch details.

**Comment by hollabaq86** [comment]
👋 I've got a few suggestions to try and solve this issue:

1. Try updating to the latest version of the SDK. There were some updates in [4.8.0](https://github.com/braintree/braintree_ruby/blob/master/CHANGELOG.md#480) that _may_ resolve this issue.
2. If that doesn't resolve this issue, can you contact [Braintree Technical Support](https://developer.paypal.com/braintree/help/) with the following info:

- timestamps of failed calls
- example params for these calls that are returning blank validation errors

There may be an issue with the API that Technical Support can help investigate further and loop in the correct API-facing teams.

**Comment by acaporrini** [comment]
Hi @hollabaq86 thanks for the reply! 

In your knowledge are there breaking changes from 4.2.0 to 4.8.0? 
What we use from the sdk aside creating the transaction:

- `gateway.customer.find`
- `default_payment_method` on customer response
- From default_payment_method response `default_payment_method.nonce.payment_method_nonce.nonce`

Thank you!
