### ISSUE TITLE
payment_receipt and global_id attributes not accessible

### ISSUE THREAD

**Issue by rachelkirk** [braintree/braintree_ruby#234]
### General information

* SDK/Library version: 4.12.0
* Environment: Sandbox and Production
* Language, language version, and OS: Ruby, 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin21], Ubuntu

### Issue description

I am trying to access the `global_id` under the `payment_receipt` object in the [docs here](https://developer.paypal.com/braintree/docs/reference/response/transaction/ruby#global_id). `payment_receipt` is not currently an attribute in the [transaction class](https://github.com/braintree/braintree_ruby/blob/master/lib/braintree/transaction.rb) in version 4.12.0 (which I'm using via the [ActiveMerchant](https://github.com/activemerchant/active_merchant) library) or the most current 4.13.0 version. When I try to access either `global_id` or `payment_receipt` I get a `NoMethodError`.

`NoMethodError: undefined method `payment_receipt' for #<Braintree::Transaction:0x00007fb3fd4e60c0>
  Did you mean?  payment_instrument_type`

When I run a remote test via ActiveMerchant and also when I look at production transcripts, I can see that Braintree is sending global_id in two places in the response, both as a top level field and nested within `payment_receipt`. 

This is the response part of a transcript obtained via a remote purchase test in debug mode:
[Braintree] <transaction>
[Braintree]   <id>me6wj9cv</id>
[Braintree]   <status>submitted_for_settlement</status>
[Braintree]   <type>sale</type>
[Braintree]   <currency-iso-code>USD</currency-iso-code>
[Braintree]   <amount>1.00</amount>
[Braintree]   <amount-requested>1.00</amount-requested>
[Braintree]   <merchant-account-id>spreedly</merchant-account-id>
[Braintree]   <sub-merchant-account-id nil="true"/>
[Braintree]   <master-merchant-account-id nil="true"/>
[Braintree]   <order-id nil="true"/>
[Braintree]   <created-at type="datetime">2023-09-13T21:42:43Z</created-at>
[Braintree]   <updated-at type="datetime">2023-09-13T21:42:44Z</updated-at>
[Braintree]   <customer>
[Braintree]     <id nil="true"/>
[Braintree]     <first-name>Longbob</first-name>
[Braintree]     <last-name>Longsen</last-name>
[Braintree]     <company nil="true"/>
[Braintree]     <email nil="true"/>
[Braintree]     <website nil="true"/>
[Braintree]     <phone nil="true"/>
[Braintree]     <fax nil="true"/>
[Braintree]   </customer>
[Braintree]   <billing>
[Braintree]     <id nil="true"/>
[Braintree]     <first-name nil="true"/>
[Braintree]     <last-name nil="true"/>
[Braintree]     <company nil="true"/>
[Braintree]     <street-address nil="true"/>
[Braintree]     <extended-address nil="true"/>
[Braintree]     <locality nil="true"/>
[Braintree]     <region nil="true"/>
[Braintree]     <postal-code nil="true"/>
[Braintree]     <country-name nil="true"/>
[Braintree]     <country-code-alpha2 nil="true"/>
[Braintree]     <country-code-alpha3 nil="true"/>
[Braintree]     <country-code-numeric nil="true"/>
[Braintree]   </billing>
[Braintree]   <refund-id nil="true"/>
[Braintree]   <refund-ids type="array"/>
[Braintree]   <refunded-transaction-id nil="true"/>
[Braintree]   <partial-settlement-transaction-ids type="array"/>
[Braintree]   <authorized-transaction-id nil="true"/>
[Braintree]   <settlement-batch-id nil="true"/>
[Braintree]   <shipping>
[Braintree]     <id nil="true"/>
[Braintree]     <first-name nil="true"/>
[Braintree]     <last-name nil="true"/>
[Braintree]     <company nil="true"/>
[Braintree]     <street-address nil="true"/>
[Braintree]     <extended-address nil="true"/>
[Braintree]     <locality nil="true"/>
[Braintree]     <region nil="true"/>
[Braintree]     <postal-code nil="true"/>
[Braintree]     <country-name nil="true"/>
[Braintree]     <country-code-alpha2 nil="true"/>
[Braintree]     <country-code-alpha3 nil="true"/>
[Braintree]     <country-code-numeric nil="true"/>
[Braintree]   </shipping>
[Braintree]   <custom-fields/>
[Braintree]   <account-funding-transaction type="boolean">false</account-funding-transaction>
[Braintree]   <avs-error-response-code nil="true"/>
[Braintree]   <avs-postal-code-response-code>I</avs-postal-code-response-code>
[Braintree]   <avs-street-address-response-code>I</avs-street-address-response-code>
[Braintree]   <cvv-response-code>M</cvv-response-code>
[Braintree]   <gateway-rejection-reason nil="true"/>
[Braintree]   <processor-authorization-code>M18KVL</processor-authorization-code>
[Braintree]   <processor-response-code>1000</processor-response-code>
[Braintree]   <processor-response-text>Approved</processor-response-text>
[Braintree]   <additional-processor-response nil="true"/>
[Braintree]   <voice-referral-number nil="true"/>
[Braintree]   <purchase-order-number nil="true"/>
[Braintree]   <tax-amount nil="true"/>
[Braintree]   <tax-exempt type="boolean">false</tax-exempt>
[Braintree]   <sca-exemption-requested nil="true"/>
[Braintree]   <processed-with-network-token type="boolean">false</processed-with-network-token>
[Braintree]   <credit-card>
[Braintree]     <token nil="true"/>
[Braintree]     <bin>510510</bin>
[Braintree]     <last-4>5100</last-4>
[Braintree]     <card-type>MasterCard</card-type>
[Braintree]     <expiration-month>09</expiration-month>
[Braintree]     <expiration-year>2024</expiration-year>
[Braintree]     <customer-location>US</customer-location>
[Braintree]     <cardholder-name>Longbob Longsen</cardholder-name>
[Braintree]     <image-url>https://assets.braintreegateway.com/payment_method_logo/mastercard.png?environment=sandbox</image-url>
[Braintree]     <is-network-tokenized type="boolean">false</is-network-tokenized>
[Braintree]     <prepaid>Unknown</prepaid>
[Braintree]     <healthcare>Unknown</healthcare>
[Braintree]     <debit>Unknown</debit>
[Braintree]     <durbin-regulated>Unknown</durbin-regulated>
[Braintree]     <commercial>Unknown</commercial>
[Braintree]     <payroll>Unknown</payroll>
[Braintree]     <issuing-bank>Unknown</issuing-bank>
[Braintree]     <country-of-issuance>Unknown</country-of-issuance>
[Braintree]     <product-id>Unknown</product-id>
[Braintree]     <global-id nil="true"/>
[Braintree]     <account-type nil="true"/>
[Braintree]     <unique-number-identifier nil="true"/>
[Braintree]     <venmo-sdk type="boolean">false</venmo-sdk>
[Braintree]     <account-balance nil="true"/>
[Braintree]   </credit-card>
[Braintree]   <status-history type="array">
[Braintree]     <status-event>
[Braintree]       <timestamp type="datetime">2023-09-13T21:42:44Z</timestamp>
[Braintree]       <status>authorized</status>
[Braintree]       <amount>1.00</amount>
[Braintree]       <user>ntalbott</user>
[Braintree]       <transaction-source>api</transaction-source>
[Braintree]     </status-event>
[Braintree]     <status-event>
[Braintree]       <timestamp type="datetime">2023-09-13T21:42:44Z</timestamp>
[Braintree]       <status>submitted_for_settlement</status>
[Braintree]       <amount>1.00</amount>
[Braintree]       <user>ntalbott</user>
[Braintree]       <transaction-source>api</transaction-source>
[Braintree]     </status-event>
[Braintree]   </status-history>
[Braintree]   <plan-id nil="true"/>
[Braintree]   <subscription-id nil="true"/>
[Braintree]   <subscription>
[Braintree]     <billing-period-end-date nil="true"/>
[Braintree]     <billing-period-start-date nil="true"/>
[Braintree]   </subscription>
[Braintree]   <add-ons type="array"/>
[Braintree]   <discounts type="array"/>
[Braintree]   <descriptor>
[Braintree]     <name nil="true"/>
[Braintree]     <phone nil="true"/>
[Braintree]     <url nil="true"/>
[Braintree]   </descriptor>
[Braintree]   <recurring type="boolean">false</recurring>
[Braintree]   <channel nil="true"/>
[Braintree]   <service-fee-amount nil="true"/>
[Braintree]   <escrow-status nil="true"/>
[Braintree]   <disbursement-details>
[Braintree]     <disbursement-date nil="true"/>
[Braintree]     <settlement-amount nil="true"/>
[Braintree]     <settlement-currency-iso-code nil="true"/>
[Braintree]     <settlement-currency-exchange-rate nil="true"/>
[Braintree]     <settlement-base-currency-exchange-rate nil="true"/>
[Braintree]     <funds-held nil="true"/>
[Braintree]     <success nil="true"/>
[Braintree]   </disbursement-details>
[Braintree]   <disputes type="array"/>
[Braintree]   <ach-return-responses type="array"/>
[Braintree]   <authorization-adjustments type="array"/>
[Braintree]   <payment-instrument-type>credit_card</payment-instrument-type>
[Braintree]   <processor-settlement-response-code></processor-settlement-response-code>
[Braintree]   <processor-settlement-response-text></processor-settlement-response-text>
[Braintree]   <network-response-code>XX</network-response-code>
[Braintree]   <network-response-text>sample network response text</network-response-text>
[Braintree]   <merchant-advice-code nil="true"/>
[Braintree]   <merchant-advice-code-text nil="true"/>
[Braintree]   <risk-data>
[Braintree]     <id>me6wj9cv</id>
[Braintree]     <decision>Approve</decision>
[Braintree]     <fraud-service-provider>fraud_protection</fraud-service-provider>
[Braintree]     <device-data-captured type="boolean">false</device-data-captured>
[Braintree]     <liability-shift nil="true"/>
[Braintree]     <decision-reasons type="array"/>
[Braintree]   </risk-data>
[Braintree]   <three-d-secure-info nil="true"/>
[Braintree]   <ships-from-postal-code nil="true"/>
[Braintree]   <shipping-amount nil="true"/>
[Braintree]   <discount-amount nil="true"/>
[Braintree]   <network-transaction-id>020230913214244</network-transaction-id>
[Braintree]   <processor-response-type>approved</processor-response-type>
[Braintree]   <authorization-expires-at type="datetime">2023-09-20T21:42:44Z</authorization-expires-at>
[Braintree]   <retry-ids type="array"/>
[Braintree]   <retried-transaction-id nil="true"/>
[Braintree]   <refund-global-ids type="array"/>
[Braintree]   <partial-settlement-transaction-global-ids type="array"/>
[Braintree]   <refunded-transaction-global-id nil="true"/>
[Braintree]   <authorized-transaction-global-id nil="true"/>
**_### [Braintree]   <global-id>dHJhbnNhY3Rpb25fbWU2d2o5Y3Y</global-id>_**
[Braintree]   <retry-global-ids type="array"/>
[Braintree]   <retried-transaction-global-id nil="true"/>
[Braintree]   <retrieval-reference-number>1234567</retrieval-reference-number>
[Braintree]   <ach-return-code nil="true"/>
[Braintree]   <installment-count nil="true"/>
[Braintree]   <installments type="array"/>
[Braintree]   <refunded-installments type="array"/>
[Braintree]   <response-emv-data nil="true"/>
[Braintree]   <acquirer-reference-number nil="true"/>
[Braintree]   <merchant-identification-number nil="true"/>
[Braintree]   <terminal-identification-number nil="true"/>
[Braintree]   <merchant-name>DESCRIPTOR</merchant-name>
[Braintree]   <merchant-address>
[Braintree]     <street-address nil="true"/>
[Braintree]     <locality nil="true"/>
[Braintree]     <region nil="true"/>
[Braintree]     <postal-code nil="true"/>
[Braintree]     <phone nil="true"/>
[Braintree]   </merchant-address>
[Braintree]   <pin-verified type="boolean">false</pin-verified>
[Braintree]   <debit-network nil="true"/>
[Braintree]   <processing-mode nil="true"/>
[Braintree]   <payment-receipt>
[Braintree]     <id>me6wj9cv</id>
_**### [Braintree]     <global-id>dHJhbnNhY3Rpb25fbWU2d2o5Y3Y</global-id>**_
[Braintree]     <amount>1.00</amount>
[Braintree]     <currency-iso-code>USD</currency-iso-code>
[Braintree]     <processor-response-code>1000</processor-response-code>
[Braintree]     <processor-response-text>Approved</processor-response-text>
[Braintree]     <processor-authorization-code>M18KVL</processor-authorization-code>
[Braintree]     <merchant-name>DESCRIPTOR</merchant-name>
[Braintree]     <merchant-address>
[Braintree]       <street-address nil="true"/>
[Braintree]       <locality nil="true"/>
[Braintree]       <region nil="true"/>
[Braintree]       <postal-code nil="true"/>
[Braintree]       <phone nil="true"/>
[Braintree]     </merchant-address>
[Braintree]     <merchant-identification-number nil="true"/>
[Braintree]     <terminal-identification-number nil="true"/>
[Braintree]     <type>sale</type>
[Braintree]     <pin-verified type="boolean">false</pin-verified>
[Braintree]     <processing-mode nil="true"/>
[Braintree]     <network-identification-code nil="true"/>
[Braintree]     <card-type>MasterCard</card-type>
[Braintree]     <card-last-4>5100</card-last-4>
[Braintree]     <account-balance nil="true"/>
[Braintree]   </payment-receipt>
[Braintree] </transaction>

**Comment by rachelkirk** [comment]
Oh goodness, github did not like my transcript example. I will attach as a file.

**Comment by rachelkirk** [comment]
[braintree_transcript.txt](https://github.com/braintree/braintree_ruby/files/12602179/braintree_transcript.txt)

**Comment by hollabaq86** [comment]
👋 @rachelkirk we released version 4.14.0 which includes these attributes. The ActiveMerchant library will need to update to this version for you to have access to these attributes. Thanks again for reaching out!
