### ISSUE TITLE
The documentation doesn't explain how to set currencies

### ISSUE THREAD

**Issue by JohnSmall** [braintree/braintree_ruby#41]
I need to accept payments in currencies other than USD. I can see a nice long list of currency codes, but no documentation explaining how to set the the currency for a transaction. 

In Ruby I tried 
    Braintree::Transaction.sale(:amount=>'10',:currency=>'GBP',etc

and got an error saying that :currency is an invalid key.

So if currency isn't specified along with the amount where is it specific. In the address?

The documents need to be amended to tell people how to specify currencies. 

Thanks

John Small

**Comment by pargunan** [comment]
This is the procedure the set the currency.
1. Navigate to Settings > Processing
2. Scroll down to Merchant Accounts
3. Click the New Sandbox Merchant Account button
4. Enter a Merchant Account ID
5. Select the currency you’d like to test in

**Comment by pargunan** [comment]
This is the procedure to set the currency
1. Navigate to Settings > Processing
2. Scroll down to Merchant Accounts
3. Click the New Sandbox Merchant Account button
4. Enter a Merchant Account ID
5. Select the currency you’d like to test in

**Comment by atkinson** [comment]
I'm having this issue as well. It seems to still not be documented (3 years later), and the links you provide above are now broken..

**Comment by aliahmed922** [comment]
Please tell how to add new merchant account in production I am not getting any option in processing in my live braintree?

**Comment by teddylun** [comment]
for sandbox: https://articles.braintreepayments.com/get-started/try-it-out#testing-currencies
