### ISSUE TITLE
There are never transactions when generating a sample webhook notification for SubscriptionChargedSuccessfully

### ISSUE THREAD

**Issue by oveddan** [braintree/braintree_ruby#64]
Knowing how much the user was charged can be a key reason for consuming a webhook notification for SubscriptionChargedSuccessfully (i.e. tracking revenue per use internally).  

When generating a sample webhook notification for this using Braintree::WebhookTesting - a subscription comes back with the webhook payload, but no transactions are ever a part of that webhook.

This subscription within the notification payload should contain a fake Transaction that includes a charged amount.

**Comment by raymondberg** [comment]
This is basically a duplicate, but you're right that this would make things easier. We're going to push this in an upcoming release. Closing for now, but feel free to reopen if you still have questions after the new release.
