### ISSUE TITLE
Make webhook sample notifications configurable

### ISSUE THREAD

**Issue by clemens** [braintree/braintree_ruby#68]
Hey guys,

while working on the Braintree integration for Codeship.io, we needed to test Braintree webhooks more thoroughly than your current testing facilities enable (see issues #64 and #65). I came up with a factory approach as shown here: https://gist.github.com/clemens/819ca167580f734b9e26.

Is there any interest from your side in integrating this? If yes, I could add tests and turn it into a proper pull request ...

Cheers,
- Clemens

**Comment by dewyze** [comment]
Closing. @clemens feel free to reopen if you have a PR you want to submit.
