### ISSUE TITLE
Get subscription's plan

### ISSUE THREAD

**Issue by fabrouy** [braintree/braintree_ruby#83]
Hi guys,

Is there a way to get a subscription's plan that I am not seeing?

I created this: 

**UPDATED**

```ruby
module Braintree
	class Subscription
		def plan
			Braintree::Plan.all.detect { |plan| plan.id == self.plan_id }
		end
	end
end
```

Cheers!

**Comment by chrissiedeist** [comment]
Your proposed implementation of Subscription#plan would indeed work (though perhaps replace 'select' with 'detect' so that you don't need to use 'p.first'). We'll take this into consideration as a feature enhancement.

**Comment by fabrouy** [comment]
Indeed! Let me update the code for you. 

Looking forward for the gem update.

Cheers!
