### ISSUE TITLE
Merchant Account addresses don't include :extended_address attribute

### ISSUE THREAD

**Issue by jtkendall** [braintree/braintree_ruby#85]
The [reference](https://developers.braintreepayments.com/ios+ruby/reference/request/merchant-account/create#individual.address.extended_address) on the Braintree developer site says that both a Merchant Account's individual and business details support `:extended_address` however this gem doesn't support it. It instead throws an invalid keys argument error when I try to create a merchant account with an address containing an extended address.

I've [forked this repo](https://github.com/simpleappgroup/braintree_ruby) and I believe made all of the necessary changes to support `:extended_address`. While testing against my sandbox account I can pass the `:extended_address` attribute, however it is not being returned by the server.

Has `extended_address` been deprecated or completely removed from Merchant Accounts?

**Comment by dewyze** [comment]
@jtkendall You were correct that the gem does not support it and the docs have been corrected to reflect that. Currently it not an attribute on Merchant Accounts and will not be returned from the server. We will look into adding it in the future.

Thanks for pointing that out!
