### ISSUE TITLE
Handle HTTP timeouts / errors in the Braintree gem

### ISSUE THREAD

**Issue by avinash-ananth** [braintree/braintree_ruby#88]
I received a raw Net::OpenTimeout raised when trying to created a sale through the gem. After briefly going over https://github.com/braintree/braintree_ruby/blob/36c702a81364f9cbc656af598532d92550139c3c/lib/braintree/http.rb (line 61 `def _http_do` and its usage) , it  doesn't look like HTTP errors are handled by the gem. 

I think it would nice if the connection errors can be wrapped up as Braintree errors  as it keeps the error handling blocks homogenous on the user's side.

**Comment by ryanjpodonnell** [comment]
Wrapping `Net::OpenTimeout` exceptions into something like `Braintree::TimeoutError` seems reasonable although implementing this change could break merchants current integrations in the chance they are catching `Net::OpenTimeout`.
We appreciate the feedback and will look into this in future major version releases.

**Comment by atomanyih** [comment]
We saw an `Errno::ETIMEDOUT` that didn't get caught by the braintree client. We also think it would be nice to wrap that error.
