### ISSUE TITLE
Use library as objects instead as singleton

### ISSUE THREAD

**Issue by tehPlayer** [braintree/braintree_ruby#89]
Hey there,

Lets say we have SaaS that allows their clients to accept payments (such as SaaS for shops) in the way of integrating payment providers (such as Braintree :) ). Is there any possible way to do so, with this library?

Best regards,
Marcin

**Comment by wjr1985** [comment]
Hi @tehPlayer,

Our library is currently built to be a singleton. It sounds like what you're looking for is our [Partners API](https://developers.braintreepayments.com/javascript+ruby/guides/partners/overview). To find out more about the Partners API, you can send an email to solutions@braintreepayments.com.

Best,
Bill
