### ISSUE TITLE
Document how to turn off logger

### ISSUE THREAD

**Issue by PragTob** [braintree/braintree_ruby#90]
The logger is really annoying in test runs. #38 shows how to turn it off, it'd be nice though if that'd be standard behavior in a test environment ot if it'd be mentioned in the docs/more prominently (couldn't find it)

```
I, [2015-07-15T11:34:04.510229 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
.I, [2015-07-15T11:34:04.563490 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
.I, [2015-07-15T11:34:04.616058 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
.I, [2015-07-15T11:34:04.667555 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
.I, [2015-07-15T11:34:04.723047 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
.I, [2015-07-15T11:34:04.776517 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
.I, [2015-07-15T11:34:04.831169 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
.I, [2015-07-15T11:34:04.893346 #8299]  INFO -- : [Braintree] [15/Jul/2015 09:34:04 UTC] POST /transactions 201
```

**Comment by ivanovv** [comment]
you can turn logger off with something like this
```ruby 
Braintree::Gateway.new(braintree_config.merge(logger: Logger.new('/dev/null')))
```

**Comment by raymondberg** [comment]
The best documentation for this exists now within our client libraries as [sample environments](https://github.com/braintree/braintree_ruby/blob/36c702a81364f9cbc656af598532d92550139c3c/env/development.rb) or in [some](https://github.com/braintree/braintree_ruby/blob/4e6fbb048b5ad27614b938177a9875a7b229f8fd/spec/integration/braintree/add_on_spec.rb#L34) of our [tests](https://github.com/braintree/braintree_ruby/blob/05d7b6527b0f359874940b547f50ae422b7804ca/spec/integration/braintree/transaction_spec.rb#L273) or the [test helper](https://github.com/braintree/braintree_ruby/blob/4e6fbb048b5ad27614b938177a9875a7b229f8fd/spec/spec_helper.rb#L20).  We're continuing to improve the clarity of each of our client libraries, and this feedback is really helpful in focusing us!
