### ISSUE TITLE
Allow specifying braintree account per request/Sale

### ISSUE THREAD

**Issue by PragTob** [braintree/braintree_ruby#91]
Right now merchant_id, public_key, private_key are set as Singletons/globals. For a platform supporting multiple merchants with different accounts (that can't share an account and then specify different merchant_account_ids).

So it'd be great if these values could be configured on a per request basis instead of their singleton nature. E.g. like another hash option passed (merachent: id:, public_key, private_key) or an optional configuration object.

If that option exists somewhere and I didn't find it, please let me know.

As a workaround I guess one could use the Singletons and put a Mutex around it... but that's less than ideal.

Thanks,
Tobi

**Comment by openbl** [comment]
If you're hoping to use transact as different Braintree Merchants, #89 has a couple suggested approaches. If you have any questions about this please reach out to support@braintreepayments.com.

**Comment by PragTob** [comment]
Thanks @openbl - exactly what I was looking for.

It'd be great if the information from the gist could be incorporated into the docs. :) I'll have a look at the partners API as well.

**Comment by PragTob** [comment]
Sorry for going back here, but the code shown in https://gist.github.com/wjr1985/567445781a06e126a286 also isn't really threadsafe as still global values need to be changed to get the gateway in the end. It's somewhat better but still not that great...

It'd be awesome if there was a good way where one could just do:

```ruby
config = Braintree::Configuration.new params
gateway = config.gateway
```

That'd be great! :+1:
