### ISSUE TITLE
Provide a way to convert a Result into a hash

### ISSUE THREAD

**Issue by PragTob** [braintree/braintree_ruby#92]
It'd be great if a Result (answer from braintree) could have an easy conversion into a hash. Having a simple ruby structure like a hash is useful when one wants to save the response for later reference for instance as JSON/YAML/XML/whatever.

Would be great to have :+1: 

edit: Edited, I thought for an errornous result `params` returns just that but it appears to only show the original request parameters

**Comment by jaryl** [comment]
+1

**Comment by prburke** [comment]
+1 This would very helpful.  Using braintree-rails to get this functionality seems excessive.

**Comment by cbetta** [comment]
Hey @PragTob, thank you for the suggestion. I've been looking at this but it's not trivial as the objects are very differently implemented across the SDK. What would be lacking with a simple `YAML::dump(result)` or `Marshal.dump(result)`? It covers nested objects, does not require any extra code, and even supports restoring objects to original state.

**Comment by PragTob** [comment]
Hey @cbetta - fancy seeing you here :)

My use case is not restoring objects to original state, but rather having a simple representation that one can look at in the admin backend or when tracking down bugs/customer complaints. E.g. admin UI, rails console, log files or even db dumps :D 

I.e. for an errornous response it's easy to see what went wrong. The appeal of a hash to me is that I can easily convert it to whatever data structure I'd like (JSON/YAML/keep it a hash) and I can use all my standard ruby fu when working with it (select/reject/pretty printing). Plus it fits very well with what I'm accustomed to - like the `params` hash.

**Comment by cbetta** [comment]
@PragTob fancy seeing you here too! Happy to see you're using braintree :)

Cool got that, so yeah I had a look but it's not an obvious fix the way the library has been written. I started on something but it wasn't very elegant. It would take me a while to build a proper parser.

One thing I've done in the past for storing objects from APIs is to go through `YAML.dump/load` with the `safe_yaml` gem.

```ruby
require 'safe_yaml`

result = [complex object]

hash = YAML.load(YAML.dump(result), safe: true)
```

**Comment by raymondberg** [comment]
It looks like conversation has lulled here. There seems to be a good work around for the original use case (thanks, @cbetta!) and an approach using `braintree-rails`. This feature may be introduced in future library releases, but for now I'm going to close this issue. Thanks again for providing this feedback!
