### ISSUE TITLE
Customer search is capped to 10_000 records, the docs say 20_000

### ISSUE THREAD

**Issue by ivanovv** [braintree/braintree_ruby#93]
This page https://developers.braintreepayments.com/javascript+ruby/reference/request/customer/search says the search results are capped and gives a link to this page https://developers.braintreepayments.com/javascript+ruby/reference/general/searching/search-results, which in turn says: 
> We currently cap searches to 20,000 maximum results.

But when I call 
```ruby
gateway.customer.all
```
for an account that has more than 20_000 customers, the API returns only 10_000 records. Seems like a discrepancy between the docs and actual behaviour. 

Am I right in my guess that the limit is 20_000 everywhere except customer search?

**Comment by ryanjpodonnell** [comment]
Great point @ivanovv! I reviewed our search logic and we cap all searches to 10,000 results besides transaction searches which are capped at 20,000. We will update our docs to reflect this.
