### ISSUE TITLE
Gem version 3.0.0 appeared on rubygems and then disappeared

### ISSUE THREAD

**Issue by lukearndt** [braintree/braintree_ruby#99]
Hello,

A version 3.0.0 of this gem was posted on rubygems.org and subsequently removed. I have a few questions, if you'd be so kind:

- Was version 3.0.0 legitimate?
- Why was it removed?
- Are there any security issues that we need to be aware of?

Thanks,
Luke.

**Comment by openbl** [comment]
@lukearndt, there were no security issues with version 3.0.0; it was released in error (semantic versioning did not necessitate a major bump) and rereleased as [2.46.0](https://github.com/braintree/braintree_ruby/releases/tag/2.46.0). We're sorry for the inconvenience.
